// Data perusahaan dengan design system
const companiesData = [
  {
    id: 1,
    name: "Adobe",
    designSystem: "Spectrum",
    source: "https://spectrum.adobe.com/",
    biography: "",
    components: [
      "Action bar",
      "Action button",
      "Alert banner",
      "Avatar",
      "Badges",
      "Bottom sheet",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Combobox",
      "Data table",
      "Divider",
      "Help text",
      "Label",
      "Link",
      "Menus",
      "Modal",
      "Navigation bar",
      "Page header",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 2,
    name: "Alaska Airlines",
    designSystem: "Auro",
    source: "https://auro.alaskaair.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Combobox",
      "Data table",
      "Date picker",
      "Dialog",
      "Drawer",
      "Dropdown",
      "Icon",
      "Link",
      "Menus",
      "Popover",
      "Radio button",
      "Select",
      "Sidebar",
      "Snackbar",
      "Text field",
    ],
    industry: "transportation",
  },
  {
    id: 3,
    name: "Amazon",
    designSystem: "Cloudscape",
    source: "https://cloudscape.design",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "App bar",
      "Autocomplete",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Code snippet",
      "Data table",
      "Date picker",
      "Dropdown",
      "Empty state",
      "Filter input",
      "Form",
      "Icon",
      "Link",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
    ],
    industry: "tech",
  },
  {
    id: 4,
    name: "Apple",
    designSystem: "HIG",
    source: "https://developer.apple.com/design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Action bar",
      "Action list",
      "Alert banner",
      "App bar",
      "Bottom sheet",
      "Breadcrumb",
      "Button",
      "Combobox",
      "Date picker",
      "Label",
      "Menus",
      "Navigation bar",
      "Popover",
      "Progress indicator",
      "Search",
      "Segmented control",
      "Sidebar",
      "Slider",
      "Switch",
      "Text area",
      "Text field",
    ],
    industry: "tech",
  },
  {
    id: 5,
    name: "Atlassian",
    designSystem: "Design System",
    source: "https://atlassian.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "App bar",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Checkbox",
      "Code snippet",
      "Data table",
      "Date picker",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Form",
      "Icon",
      "Inline message",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Sidebar",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 6,
    name: "Audi",
    designSystem: "Design System",
    source: "https://styleguide.audi.com/document/2865?#/-/ui-introduction",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Dialog",
      "Icon",
      "Modal",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Search",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "automotive",
  },
  {
    id: 7,
    name: "Basis",
    designSystem: "Design System",
    source: "https://design.basis.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Badges",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Date picker",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Filter input",
      "Link",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 8,
    name: "Biings",
    designSystem: "Design System",
    source: "https://biings.design/#/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Alert banner", "Avatar", "Button", "Checkbox", "Data table", "Dropdown", "Form", "Link", "Menus", "Modal", "Progress indicator", "Radio button", "Segmented control", "Snackbar", "Tabs", "Tag", "Text field", "Tooltip"],
    industry: "tech",
  },
  {
    id: 9,
    name: "Brainly",
    designSystem: "Pencil",
    source: "https://design.brainly.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Badges", "Button", "Cards", "Chip", "Dialog", "Popover", "Progress bar", "Select", "Snackbar", "Tooltip"],
    industry: "education",
  },
  {
    id: 10,
    name: "Carrefour",
    designSystem: "Marcel",
    source: "https://carrefour.design",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action list",
      "Autocomplete",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Date picker",
      "Drawer",
      "Link",
      "Modal",
      "Navigation bar",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "retail",
  },
  {
    id: 11,
    name: "CBRE Build",
    designSystem: "Blocks",
    source: "",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Alert banner", "Button", "Checkbox", "Dropdown", "Link", "Modal", "Popover", "Radio button", "Segmented control", "Tabs", "Text field", "Tooltip"],
    industry: "realestate",
  },
  {
    id: 12,
    name: "Cisco",
    designSystem: "Momentum Design",
    source: "https://momentum.design",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Avatar", "Badges", "Checkbox", "Chip", "Dialog", "Divider", "List", "Progress bar", "Progress indicator", "Switch", "Tabs"],
    industry: "tech",
  },
  {
    id: 13,
    name: "Datadog",
    designSystem: "Druids",
    source: "https://druids.datadoghq.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Autocomplete",
      "Avatar",
      "Badges",
      "Button",
      "Checkbox",
      "Code snippet",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Drawer",
      "Empty state",
      "Form",
      "Icon",
      "Label",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 14,
    name: "Dell",
    designSystem: "Design System",

    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Filter input",
      "Form",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Select",
      "Sidebar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 15,
    name: "Docplanner",
    designSystem: "Watson",
    source: "https://watson.github.io/design-system/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Combobox",
      "Data table",
      "Date picker",
      "Divider",
      "Empty state",
      "Icon",
      "Link",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Sidebar",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "healthcare",
  },
  {
    id: 16,
    name: "eBay",
    designSystem: "Evo",
    source: "https://playbook.ebay.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Bottom sheet",
      "Breadcrumb",
      "Button",
      "Checkbox",
      "Chip",
      "Combobox",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Dropdown",
      "Filter input",
      "Link",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Radio button",
      "Segmented control",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "ecommerce",
  },
  {
    id: 17,
    name: "Elastic",
    designSystem: "Design System",
    source: "https://eui.elastic.co/#/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Code snippet",
      "Combobox",
      "Data table",
      "Date picker",
      "Drawer",
      "Empty state",
      "Filter input",
      "Form",
      "Icon",
      "Link",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 18,
    name: "Esri",
    designSystem: "Calcite",
    source: "https://developers.arcgis.com/calcite-design-system/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Alert banner",
      "Avatar",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Combobox",
      "Data table",
      "Date picker",
      "Drawer",
      "Dropdown",
      "Filter input",
      "Icon",
      "Label",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Slider",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 19,
    name: "General Electric",
    designSystem: "Edison",
    source: "https://eds.gehealthcare.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Alert banner",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Drawer",
      "Dropdown",
      "Filter input",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Slider",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "industrial",
  },
  {
    id: 20,
    name: "GitHub",
    designSystem: "Primer",
    source: "https://primer.style",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Action bar",
      "Action list",
      "Alert banner",
      "App bar",
      "Autocomplete",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Checkbox",
      "Chip",
      "Data table",
      "Dialog",
      "Icon",
      "Label",
      "Link",
      "Menus",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 21,
    name: "GitLab",
    designSystem: "Pajamas",
    source: "https://design.gitlab.com",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Combobox",
      "Data table",
      "Date picker",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Filter input",
      "Label",
      "Link",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 22,
    name: "Google",
    designSystem: "Material Design",
    source: "https://m3.material.io/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Action list",
      "App bar",
      "Badges",
      "Bottom sheet",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Date picker",
      "Dialog",
      "Divider",
      "Drawer",
      "Menus",
      "Navigation bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 23,
    name: "GOV.UK",
    designSystem: "Design System",
    source: "https://design-system.service.gov.uk/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Accordion", "Alert banner", "Breadcrumb", "Button", "Checkbox", "Data table", "Date picker", "Form", "Link", "List", "Page header", "Pagination", "Radio button", "Select", "Tabs", "Tag", "Text area", "Text field"],
    industry: "government",
  },
  {
    id: 24,
    name: "Gusto",
    designSystem: "Workbench",
    source: "https://medium.com/gusto-design",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Alert banner",
      "Autocomplete",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Dialog",
      "Drawer",
      "Form",
      "Icon",
      "Link",
      "List",
      "Menus",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
    ],
    industry: "finance",
  },
  {
    id: 25,
    name: "Helly Hansen",
    designSystem: "Design System",
    source: "https://design.hellyhansen.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Accordion", "Alert banner", "Avatar", "Button", "Cards", "Checkbox", "Data table", "Divider", "Dropdown", "Link", "List", "Modal", "Page header", "Radio button", "Switch", "Tabs", "Tag", "Text field", "Tooltip"],
    industry: "retail",
  },
  {
    id: 26,
    name: "IBM",
    designSystem: "Carbon",
    source: "https://carbondesignsystem.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Code snippet",
      "Data table",
      "Date picker",
      "Dropdown",
      "Form",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 27,
    name: "Ideagen",
    designSystem: "Helix",
    source: "https://www.helixui.com/9904796d6/p/19ace3-helix",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Empty state",
      "Link",
      "Menus",
      "Modal",
      "Page header",
      "Pagination",
      "Progress bar",
      "Radio button",
      "Search",
      "Select",
      "Sidebar",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 28,
    name: "INPS",
    designSystem: "Sirio",
    source: "https://www.inps.design/3e7e2b0f5/p/69d0de-introduzione",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Date picker",
      "Dialog",
      "Dropdown",
      "Navigation bar",
      "Page header",
      "Pagination",
      "Progress bar",
      "Radio button",
      "Search",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "government",
  },
  {
    id: 29,
    name: "Kajabi",
    designSystem: "Sage",
    source: "https://sage.kajabi.com/pages/index",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Divider",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Icon",
      "Label",
      "Link",
      "List",
      "Modal",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Sidebar",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 30,
    name: "Kiwicom",
    designSystem: "Orbit",
    source: "https://orbit.kiwi/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action list",
      "Alert banner",
      "App bar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Data table",
      "Dialog",
      "Divider",
      "Drawer",
      "Empty state",
      "Icon",
      "Link",
      "List",
      "Modal",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "transportation",
  },
  {
    id: 31,
    name: "Lemon Squeezy",
    designSystem: "Wedges",
    source: "https://www.lemonsqueezy.com/wedges",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Avatar",
      "Badges",
      "Button",
      "Button group",
      "Checkbox",
      "Dropdown",
      "Label",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 32,
    name: "Line",
    designSystem: "Design System",
    source: "https://designsystem.line.me/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Avatar",
      "Badges",
      "Bottom sheet",
      "Button",
      "Checkbox",
      "Chip",
      "Dialog",
      "Menus",
      "Navigation bar",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 33,
    name: "LocalTapiola",
    designSystem: "Duet",
    source: "https://www.duetds.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Action button",
      "Alert banner",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Combobox",
      "Data table",
      "Date picker",
      "Divider",
      "Empty state",
      "Icon",
      "Label",
      "Link",
      "List",
      "Modal",
      "Navigation bar",
      "Page header",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Slider",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "finance",
  },
  {
    id: 34,
    name: "Michelin",
    designSystem: "Motion",
    source: "https://designsystem.michelin.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Dropdown",
      "Icon",
      "Label",
      "Link",
      "Modal",
      "Navigation bar",
      "Page header",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Sidebar",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "automotive",
  },
  {
    id: 35,
    name: "Microsoft",
    designSystem: "Fluent 2",
    source: "https://fluent2.microsoft.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Avatar",
      "Badges",
      "Button",
      "Cards",
      "Checkbox",
      "Combobox",
      "Dialog",
      "Divider",
      "Dropdown",
      "Icon",
      "Label",
      "Link",
      "Menus",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Slider",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 36,
    name: "Monday.com",
    designSystem: "Vide",
    source: "https://vibe.monday.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Checkbox",
      "Chip",
      "Combobox",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Dropdown",
      "Icon",
      "Label",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 37,
    name: "MongoDB",
    designSystem: "LeafyGreen",
    source: "https://www.mongodb.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Code snippet",
      "Combobox",
      "Data table",
      "Date picker",
      "Empty state",
      "Form",
      "Icon",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Sidebar",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 38,
    name: "Motorway",
    designSystem: "Highway Code",
    source: "https://thc.motorway.co.uk/0566ad526/p/652544-the-highway-code",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Alert banner", "Badges", "Button", "Checkbox", "Chip", "Date picker", "Empty state", "Form", "Icon", "Link", "Progress bar", "Progress indicator", "Radio button", "Select", "Snackbar", "Switch", "Text area", "Text field"],
    industry: "automotive",
  },
  {
    id: 39,
    name: "Mozilla",
    designSystem: "Protocol",
    source: "https://protocol.mozilla.org/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Accordion", "Breadcrumb", "Button", "Cards", "Checkbox", "Data table", "Date picker", "Form", "Link", "List", "Menus", "Modal", "Radio button", "Search", "Select", "Sidebar", "Text area", "Text field"],
    industry: "tech",
  },
  {
    id: 40,
    name: "Nordhealth",
    designSystem: "Design System",
    source: "https://nordhealth.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "App bar",
      "Avatar",
      "Badges",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Divider",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Icon",
      "Menus",
      "Modal",
      "Page header",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "healthcare",
  },
  {
    id: 41,
    name: "NS",
    designSystem: "Tractie",
    source: "https://tractie.ns.nl/2e23992f3/p/226ce1-tractie--ns-design-system",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Action list",
      "Alert banner",
      "Badges",
      "Breadcrumb",
      "Button",
      "Checkbox",
      "Chip",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Form",
      "Help text",
      "Icon",
      "Label",
      "Link",
      "List",
      "Navigation bar",
      "Page header",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "transportation",
  },
  {
    id: 42,
    name: "Ontario",
    designSystem: "Design System",
    source: "https://designsystem.ontario.ca/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Badges",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Dropdown",
      "Icon",
      "Label",
      "Page header",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Text area",
      "Text field",
    ],
    industry: "government",
  },
  {
    id: 43,
    name: "Orange",
    designSystem: "Design System",
    source: "https://system.design.orange.com/0c1af118d/p/0127c5-the-orange-design-system",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Dropdown",
      "Form",
      "Modal",
      "Navigation bar",
      "Page header",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Sidebar",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 44,
    name: "Palantir",
    designSystem: "Blueprint",
    source: "https://blueprintjs.com/docs/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "App bar",
      "Autocomplete",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Drawer",
      "Empty state",
      "Form",
      "Icon",
      "Label",
      "Menus",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 45,
    name: "Pinterest",
    designSystem: "Gestalt",
    source: "https://gestalt.pinterest.systems/home",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Avatar",
      "Badges",
      "Button",
      "Button group",
      "Checkbox",
      "Combobox",
      "Data table",
      "Date picker",
      "Divider",
      "Dropdown",
      "Form",
      "Icon",
      "Label",
      "Link",
      "List",
      "Modal",
      "Page header",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 46,
    name: "Pluralsight",
    designSystem: "Design System",
    source: "https://pando.pluralsight.com/92687036d/p/38aa59-psds-classic-docs-map",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "App bar",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Code snippet",
      "Data table",
      "Date picker",
      "Dialog",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Form",
      "Icon",
      "Label",
      "Link",
      "List",
      "Menus",
      "Page header",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Segmented control",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "education",
  },
  {
    id: 47,
    name: "Porsche",
    designSystem: "Design System",
    source: "https://designsystems.surf/products/design-system-reality-check",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Button",
      "Button group",
      "Checkbox",
      "Data table",
      "Divider",
      "Drawer",
      "Icon",
      "Inline message",
      "Link",
      "List",
      "Modal",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
    ],
    industry: "automotive",
  },
  {
    id: 48,
    name: "Razorpay",
    designSystem: "Blade",
    source: "https://blade.razorpay.com/?path=/docs/guides-intro--docs",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Badges",
      "Bottom sheet",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Divider",
      "Drawer",
      "Dropdown",
      "Icon",
      "Link",
      "List",
      "Modal",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "finance",
  },
  {
    id: 49,
    name: "Red Hat",
    designSystem: "PatternFly",
    source: "https://www.patternfly.org/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Action list",
      "Alert banner",
      "App bar",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Code snippet",
      "Data table",
      "Date picker",
      "Divider",
      "Drawer",
      "Dropdown",
      "Empty state",
      "Form",
      "Help text",
      "Icon",
      "List",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Select",
      "Sidebar",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 50,
    name: "Rei",
    designSystem: "Cedar",
    source: "https://cedar.rei.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Icon",
      "Link",
      "List",
      "Modal",
      "Pagination",
      "Popover",
      "Radio button",
      "Segmented control",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text field",
      "Tooltip",
    ],
    industry: "retail",
  },
  {
    id: 51,
    name: "Salesforce",
    designSystem: "Lightning",
    source: "https://www.lightningdesignsystem.com/2e1ef8501",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Combobox",
      "Data table",
      "Date picker",
      "Drawer",
      "Empty state",
      "Form",
      "Icon",
      "Inline message",
      "Menus",
      "Modal",
      "Page header",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 52,
    name: "Samsung",
    designSystem: "One UI",
    source: "https://developer.samsung.com/one-ui",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["App bar", "Button", "Dialog", "List", "Navigation bar", "Search", "Snackbar", "Tabs"],
    industry: "tech",
  },
  {
    id: 53,
    name: "Seek",
    designSystem: "Braid",
    source: "https://seek-oss.github.io/braid-design-system/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Badges",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Dialog",
      "Divider",
      "Drawer",
      "Dropdown",
      "Label",
      "List",
      "Menus",
      "Pagination",
      "Progress indicator",
      "Radio button",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 54,
    name: "Segment",
    designSystem: "Evergreen",
    source: "https://evergreen.segment.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Autocomplete",
      "Avatar",
      "Badges",
      "Button",
      "Checkbox",
      "Combobox",
      "Data table",
      "Dialog",
      "Drawer",
      "Empty state",
      "Menus",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Search",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 55,
    name: "ServiceNow",
    designSystem: "Horizon",
    source: "https://horizon.servicenow.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Date picker",
      "Dropdown",
      "Empty state",
      "Icon",
      "Label",
      "Link",
      "Menus",
      "Modal",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 56,
    name: "Shopify",
    designSystem: "Polaris",
    source: "https://polaris-react.shopify.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Action list",
      "Alert banner",
      "App bar",
      "Autocomplete",
      "Avatar",
      "Badges",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Combobox",
      "Data table",
      "Date picker",
      "Divider",
      "Empty state",
      "Filter input",
      "Form",
      "Icon",
      "Inline message",
      "Link",
      "List",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "ecommerce",
  },
  {
    id: 57,
    name: "Skoda",
    designSystem: "Flow",
    source: "https://flow.skoda-brand.com/d/6aQMrmD6PhWL",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Bottom sheet",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Label",
      "List",
      "Menus",
      "Modal",
      "Navigation bar",
      "Pagination",
      "Progress indicator",
      "Radio button",
      "Search",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text field",
    ],
    industry: "automotive",
  },
  {
    id: 58,
    name: "Sprout Social",
    designSystem: "Design System",
    source: "https://seeds.sproutsocial.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Date picker",
      "Drawer",
      "Empty state",
      "Form",
      "Icon",
      "Label",
      "Link",
      "Menus",
      "Modal",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 59,
    name: "SumUp",
    designSystem: "Circuit",
    source: "https://circuit.sumup.com/?path=/docs/introduction-welcome--docs",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Avatar",
      "Badges",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Date picker",
      "Dialog",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Search",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "finance",
  },
  {
    id: 60,
    name: "Sunrise",
    designSystem: "Solar",
    source: "https://design.sunrise.fr/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Dropdown",
      "Filter input",
      "Form",
      "List",
      "Page header",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Slider",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 61,
    name: "Teamleader",
    designSystem: "Ahoy",
    source: "https://ahoy.teamleader.design/3547946e7/p/223d3f-ahoy",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Action bar",
      "Alert banner",
      "Avatar",
      "Badges",
      "Button",
      "Cards",
      "Data table",
      "Date picker",
      "Dialog",
      "Empty state",
      "Filter input",
      "Label",
      "Menus",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Sidebar",
      "Snackbar",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 62,
    name: "Thumbtack",
    designSystem: "Thumbprint",
    source: "https://thumbprint.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Alert banner",
      "Avatar",
      "Button",
      "Button group",
      "Checkbox",
      "Chip",
      "Date picker",
      "Dropdown",
      "Help text",
      "Label",
      "Link",
      "List",
      "Modal",
      "Navigation bar",
      "Popover",
      "Progress indicator",
      "Radio button",
      "Snackbar",
      "Switch",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 63,
    name: "Twilio",
    designSystem: "Paste",
    source: "https://paste.twilio.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Code snippet",
      "Combobox",
      "Data table",
      "Date picker",
      "Divider",
      "Drawer",
      "Form",
      "Help text",
      "Icon",
      "Label",
      "List",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress indicator",
      "Select",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 64,
    name: "U.S. Web",
    designSystem: "Design System",
    source: "https://designsystem.digital.gov/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Breadcrumb",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Combobox",
      "Data table",
      "Date picker",
      "Form",
      "Icon",
      "Link",
      "List",
      "Modal",
      "Page header",
      "Pagination",
      "Progress bar",
      "Radio button",
      "Search",
      "Select",
      "Sidebar",
      "Slider",
      "Tag",
      "Text field",
      "Tooltip",
    ],
    industry: "government",
  },
  {
    id: 65,
    name: "UAE",
    designSystem: "Design System",
    source: "https://designsystem.gov.ae/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Date picker",
      "Dropdown",
      "Link",
      "Modal",
      "Navigation bar",
      "Pagination",
      "Popover",
      "Progress bar",
      "Radio button",
      "Select",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "government",
  },
  {
    id: 66,
    name: "Uber",
    designSystem: "Base",
    source: "https://base.uber.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "App bar",
      "Avatar",
      "Badges",
      "Bottom sheet",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Drawer",
      "Empty state",
      "Link",
      "Menus",
      "Modal",
      "Navigation bar",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Tag",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "transportation",
  },
  {
    id: 67,
    name: "Vercel",
    designSystem: "Geist",
    source: "https://designsystems.surf/design-systems/vercel",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Checkbox",
      "Code snippet",
      "Combobox",
      "Data table",
      "Date picker",
      "Drawer",
      "Empty state",
      "Menus",
      "Modal",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
      "Tree view",
    ],
    industry: "tech",
  },
  {
    id: 68,
    name: "Visa",
    designSystem: "Design System",
    source: "https://design.visa.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Badges",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Combobox",
      "Data table",
      "Date picker",
      "Dialog",
      "Divider",
      "Dropdown",
      "Icon",
      "Link",
      "List",
      "Navigation bar",
      "Pagination",
      "Progress bar",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Slider",
      "Switch",
      "Tabs",
      "Text field",
      "Tooltip",
    ],
    industry: "finance",
  },
  {
    id: 69,
    name: "Washington Post",
    designSystem: "Design System",
    source: "https://build.washingtonpost.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Button",
      "Cards",
      "Checkbox",
      "Dialog",
      "Divider",
      "Drawer",
      "Icon",
      "Menus",
      "Navigation bar",
      "Pagination",
      "Popover",
      "Radio button",
      "Search",
      "Select",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "media",
  },
  {
    id: 70,
    name: "Wikimedia",
    designSystem: "Codex",
    source: "https://doc.wikimedia.org/codex/latest/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Autocomplete",
      "Avatar",
      "Button",
      "Button group",
      "Cards",
      "Checkbox",
      "Chip",
      "Combobox",
      "Dialog",
      "Icon",
      "Label",
      "Link",
      "Menus",
      "Progress bar",
      "Radio button",
      "Search",
      "Select",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
    ],
    industry: "tech",
  },
  {
    id: 71,
    name: "Wise",
    designSystem: "Design System",
    source: "https://wise.design/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Alert banner", "Avatar", "Bottom sheet", "Button", "Checkbox", "Chip", "Date picker", "Dropdown", "Modal", "Popover", "Radio button", "Search", "Snackbar", "Switch", "Tabs", "Text area", "Text field"],
    industry: "finance",
  },
  {
    id: 72,
    name: "Wonderflow",
    designSystem: "Wanda",
    source: "https://design.wonderflow.ai/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Autocomplete",
      "Avatar",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Divider",
      "Drawer",
      "Icon",
      "List",
      "Menus",
      "Modal",
      "Pagination",
      "Popover",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Slider",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 73,
    name: "Workday",
    designSystem: "Canvas",
    source: "https://canvas.workday.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Action bar",
      "Breadcrumb",
      "Button",
      "Cards",
      "Checkbox",
      "Chip",
      "Data table",
      "Dialog",
      "Form",
      "Menus",
      "Modal",
      "Pagination",
      "Progress indicator",
      "Radio button",
      "Segmented control",
      "Select",
      "Sidebar",
      "Snackbar",
      "Switch",
      "Tabs",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
  {
    id: 74,
    name: "WorkOS",
    designSystem: "Radix",
    source: "https://www.radix-ui.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: ["Accordion", "Action bar", "Avatar", "Checkbox", "Dialog", "Form", "Label", "Link", "Menus", "Navigation bar", "Popover", "Progress bar", "Radio button", "Select", "Slider", "Snackbar", "Switch", "Tabs", "Tooltip"],
    industry: "tech",
  },
  {
    id: 75,
    name: "Zendesk",
    designSystem: "Garden",
    source: "https://garden.zendesk.com/",
    biography: "Placeholder - Biografi perusahaan akan diisi nanti",
    components: [
      "Accordion",
      "Alert banner",
      "Avatar",
      "Breadcrumb",
      "Button",
      "Checkbox",
      "Code snippet",
      "Combobox",
      "Data table",
      "Date picker",
      "Drawer",
      "List",
      "Menus",
      "Modal",
      "Pagination",
      "Progress bar",
      "Progress indicator",
      "Radio button",
      "Select",
      "Slider",
      "Switch",
      "Tabs",
      "Tag",
      "Text area",
      "Text field",
      "Tooltip",
    ],
    industry: "tech",
  },
];

// Data komponen UI yang tersedia
const allComponents = [
  "Action bar",
  "Action button",
  "Action list",
  "Alert banner",
  "App bar",
  "Autocomplete",
  "Avatar",
  "Badges",
  "Bottom sheet",
  "Breadcrumb",
  "Button",
  "Button group",
  "Cards",
  "Checkbox",
  "Chip",
  "Code snippet",
  "Combobox",
  "Data table",
  "Date picker",
  "Dialog",
  "Divider",
  "Drawer",
  "Dropdown",
  "Empty state",
  "Filter input",
  "Form",
  "Help text",
  "Icon",
  "Inline message",
  "Label",
  "Link",
  "List",
  "Menus",
  "Modal",
  "Navigation bar",
  "Page header",
  "Pagination",
  "Popover",
  "Progress bar",
  "Progress indicator",
  "Radio button",
  "Search",
  "Segmented control",
  "Select",
  "Sidebar",
  "Slider",
  "Snackbar",
  "Switch",
  "Tabs",
  "Tag",
  "Text area",
  "Text field",
  "Tooltip",
  "Tree view",
];

// State aplikasi
let currentPage = 1;
const itemsPerPage = 45;
let filteredCompanies = [...companiesData];
let filteredComponents = [...allComponents];
let selectedComponent = null; // Komponen yang sedang dipilih

// Inisialisasi aplikasi
document.addEventListener("DOMContentLoaded", function () {
  initializeApp();
  initializeDarkMode();
});

function initializeApp() {
  renderCompanyTable();
  renderComponentList();
  setupEventListeners();
  updatePagination();
  updateCompanyCount();
}

// Render tabel perusahaan
function renderCompanyTable() {
  const tbody = document.getElementById("companyTableBody");
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const companiesToShow = filteredCompanies.slice(startIndex, endIndex);

  tbody.innerHTML = companiesToShow
    .map(
      (company, index) => `
        <tr class="hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer" onclick="showCompanyDetail(${company.id})">
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                ${startIndex + index + 1}
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm font-medium text-gray-900 dark:text-white">${company.name}</div>
                <div class="text-sm text-gray-500 dark:text-gray-300">${company.industry}</div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm font-medium text-gray-900 dark:text-white">${company.designSystem}</div>
            </td>
            <td class="px-6 py-4">
                <div class="flex flex-wrap gap-1">
                     ${(() => {
                       // Jika ada komponen yang dipilih, tampilkan di urutan pertama dengan background merah
                       let displayComponents = [...company.components];
                       if (selectedComponent && company.components.includes(selectedComponent)) {
                         displayComponents = [selectedComponent, ...company.components.filter(c => c !== selectedComponent)];
                       }

                       return displayComponents
                         .slice(0, 3)
                         .map(component => {
                           const isSelected = selectedComponent === component;
                           const bgClass = isSelected ? "bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200" : "bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200";
                           return `
                              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${bgClass}">
                                  ${component}
                              </span>
                            `;
                         })
                         .join("");
                     })()}
                    ${
                      company.components.length > 3
                        ? `
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200">
                            +${company.components.length - 3}
                        </span>
                    `
                        : ""
                    }
                </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                ${company.components.length}
            </td>
        </tr>
    `
    )
    .join("");

  updatePagination();
}

// Render daftar komponen
function renderComponentList() {
  const componentList = document.getElementById("componentList");

  // Hitung frekuensi komponen
  const componentFrequency = {};
  filteredCompanies.forEach(company => {
    company.components.forEach(component => {
      componentFrequency[component] = (componentFrequency[component] || 0) + 1;
    });
  });

  // Sort berdasarkan frekuensi
  const sortedComponents = filteredComponents.sort((a, b) => {
    const freqA = componentFrequency[a] || 0;
    const freqB = componentFrequency[b] || 0;
    return freqB - freqA;
  });

  componentList.innerHTML = sortedComponents
    .map((component, index) => {
      const frequency = componentFrequency[component] || 0;
      const percentage = filteredCompanies.length > 0 ? Math.round((frequency / filteredCompanies.length) * 100) : 0;

      return `
            <div class="px-3 flex items-center justify-between py-3 hover:bg-blue-100 dark:hover:bg-blue-900 rounded cursor-pointer" onclick="filterByComponent('${component}')">
                <div class="flex items-center space-x-2">
                    <span class="text-xs font-semibold text-gray-400 dark:text-gray-500 bg-gray-100 dark:bg-gray-700 rounded-full w-6 h-6 flex items-center justify-center">${index + 1}</span>
                    <span class="text-sm text-gray-900 dark:text-white">${component}</span>
                </div>
                <div class="flex items-center space-x-2">
                    <span class="text-xs text-gray-500 dark:text-gray-400">${frequency}/${filteredCompanies.length}</span>
                    <div class="w-16 bg-gray-200 dark:bg-gray-600 rounded-full h-2">
                        <div class="bg-blue-500 h-2 rounded-full" style="width: ${percentage}%"></div>
                    </div>
                    <span class="text-xs text-gray-600 dark:text-gray-300 font-medium">${percentage}%</span>
                </div>
            </div>
        `;
    })
    .join("");
}

// Setup event listeners
function setupEventListeners() {
  // Search perusahaan
  document.getElementById("searchCompany").addEventListener("input", function (e) {
    const searchTerm = e.target.value.toLowerCase();
    filteredCompanies = companiesData.filter(
      company =>
        company.name.toLowerCase().includes(searchTerm) ||
        company.designSystem.toLowerCase().includes(searchTerm) ||
        company.biography.toLowerCase().includes(searchTerm) ||
        company.components.some(component => component.toLowerCase().includes(searchTerm))
    );
    selectedComponent = null; // Reset komponen yang dipilih
    currentPage = 1;
    renderCompanyTable();
  });

  // Filter perusahaan
  document.getElementById("filterCompany").addEventListener("change", function (e) {
    const filterValue = e.target.value;
    if (filterValue === "") {
      filteredCompanies = [...companiesData];
    } else {
      filteredCompanies = companiesData.filter(company => company.industry === filterValue);
    }
    selectedComponent = null; // Reset komponen yang dipilih
    currentPage = 1;
    renderCompanyTable();
  });

  // Search komponen
  document.getElementById("searchComponent").addEventListener("input", function (e) {
    const searchTerm = e.target.value.toLowerCase();
    filteredComponents = allComponents.filter(component => component.toLowerCase().includes(searchTerm));
    selectedComponent = null; // Reset komponen yang dipilih
    renderComponentList();
  });

  // Filter komponen
  document.getElementById("filterComponent").addEventListener("change", function (e) {
    const filterValue = e.target.value;
    if (filterValue === "") {
      filteredComponents = [...allComponents];
    } else {
      filteredComponents = allComponents.filter(component => component.toLowerCase().includes(filterValue));
    }
    selectedComponent = null; // Reset komponen yang dipilih
    renderComponentList();
  });

  // Pagination
  document.getElementById("prevPage").addEventListener("click", function () {
    if (currentPage > 1) {
      currentPage--;
      renderCompanyTable();
    }
  });

  document.getElementById("nextPage").addEventListener("click", function () {
    const totalPages = Math.ceil(filteredCompanies.length / itemsPerPage);
    if (currentPage < totalPages) {
      currentPage++;
      renderCompanyTable();
    }
  });

  // Modal
  document.getElementById("closeModal").addEventListener("click", function () {
    document.getElementById("companyModal").classList.add("hidden");
  });

  // Close modal ketika klik di luar
  document.getElementById("companyModal").addEventListener("click", function (e) {
    if (e.target === this) {
      this.classList.add("hidden");
    }
  });
}

// Filter berdasarkan komponen
function filterByComponent(component) {
  selectedComponent = component; // Simpan komponen yang dipilih
  filteredCompanies = companiesData.filter(company => company.components.includes(component));
  currentPage = 1;
  renderCompanyTable();
}

// Tampilkan detail perusahaan
function showCompanyDetail(companyId) {
  const company = companiesData.find(c => c.id === companyId);
  if (!company) return;

  document.getElementById("modalTitle").textContent = company.name;
  document.getElementById("modalContent").innerHTML = `
        <div class="space-y-4">
            <div>
                <h4 class="font-semibold text-gray-900 dark:text-white mb-2">Sumber</h4>
                <a href="${company.source || "#"}" target="_blank" class="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 underline text-sm">
                    ${company.source || "Placeholder - Link sumber akan diisi nanti"}
                </a>
            </div>
            <div>
                <h4 class="font-semibold text-gray-900 dark:text-white mb-2">Design System</h4>
                <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 dark:bg-purple-900 text-purple-800 dark:text-purple-200">
                    ${company.designSystem}
                </span>
            </div>
            <div>
                <h4 class="font-semibold text-gray-900 dark:text-white mb-2">Industri</h4>
                <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200">
                    ${company.industry}
                </span>
            </div>
          
                <h4 class="font-semibold text-gray-900 dark:text-white mb-2">Komponen UI (${company.components.length})</h4>
                <div class="flex flex-wrap gap-2">
                    ${company.components
                      .map(
                        component => `
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200">
                            ${component}
                        </span>
                    `
                      )
                      .join("")}
                </div>
            </div>
        </div>
    `;

  document.getElementById("companyModal").classList.remove("hidden");
}

// Update pagination
function updatePagination() {
  const totalPages = Math.ceil(filteredCompanies.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage + 1;
  const endIndex = Math.min(currentPage * itemsPerPage, filteredCompanies.length);

  document.getElementById("showingStart").textContent = startIndex;
  document.getElementById("showingEnd").textContent = endIndex;
  document.getElementById("totalRecords").textContent = filteredCompanies.length;
  document.getElementById("currentPage").textContent = currentPage;

  document.getElementById("prevPage").disabled = currentPage === 1;
  document.getElementById("nextPage").disabled = currentPage === totalPages || totalPages === 0;
}

// Fungsi untuk menambah data perusahaan baru
function addCompany(name, biography, components, industry) {
  const newCompany = {
    id: companiesData.length + 1,
    name: name,
    biography: biography,
    components: components,
    industry: industry,
  };
  companiesData.push(newCompany);
  filteredCompanies = [...companiesData];
  renderCompanyTable();
  renderComponentList();
}

// Fungsi untuk mengimpor data dari CSV/Excel
function importData(data) {
  // Implementasi import data dari file
  console.log("Import data:", data);
}

// Update jumlah perusahaan di header
function updateCompanyCount() {
  const countElement = document.querySelector(".bg-blue-100");
  if (countElement) {
    countElement.textContent = `${companiesData.length} Perusahaan`;
  }
}

// Dark Mode Functions
function initializeDarkMode() {
  const darkModeToggle = document.getElementById("darkModeToggle");
  const sunIcon = document.getElementById("sunIcon");
  const moonIcon = document.getElementById("moonIcon");

  // Check for saved theme preference or default to light mode
  const savedTheme = localStorage.getItem("theme");
  const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

  if (savedTheme === "dark" || (!savedTheme && prefersDark)) {
    document.documentElement.classList.add("dark");
    sunIcon.classList.add("hidden");
    moonIcon.classList.remove("hidden");
  } else {
    document.documentElement.classList.remove("dark");
    sunIcon.classList.remove("hidden");
    moonIcon.classList.add("hidden");
  }

  // Toggle dark mode - optimized for instant switching
  darkModeToggle.addEventListener("click", function () {
    const isDark = document.documentElement.classList.contains("dark");

    // Use requestAnimationFrame for smooth DOM updates
    requestAnimationFrame(() => {
      if (isDark) {
        document.documentElement.classList.remove("dark");
        localStorage.setItem("theme", "light");
        sunIcon.classList.remove("hidden");
        moonIcon.classList.add("hidden");
      } else {
        document.documentElement.classList.add("dark");
        localStorage.setItem("theme", "dark");
        sunIcon.classList.add("hidden");
        moonIcon.classList.remove("hidden");
      }
    });
  });
}

// Export data ke CSV
function exportData() {
  const csvContent =
    "data:text/csv;charset=utf-8," + "Nama Perusahaan,Design System,Industri,Komponen UI\n" + companiesData.map(company => `"${company.name}","${company.designSystem}","${company.industry}","${company.components.join(", ")}"`).join("\n");

  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", "data_perusahaan.csv");
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
